### ISSUE TITLE
uninitialized constant Aws::Ec2::Fog

### ISSUE THREAD

**Issue by jschaul** [SearchSpring/aws_security#38]
Currently released version (`0.1.9`) has the following bug (which might have been solved already by https://github.com/SearchSpring/aws_security/pull/36 - not sure):

```
* aws_security_group[<REMOVED>] action create_and_attach
           * chef_gem[fog-aws] action install (up to date)

           ================================================================================
           Error executing action `create_and_attach` on resource 'aws_security_group[<REMOVED>]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Aws::Ec2::Fog

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/aws_security/libraries/ec2.rb:50:in `create_aws_interface'
           /tmp/kitchen/cache/cookbooks/aws_security/libraries/ec2.rb:23:in `ec2'
           /tmp/kitchen/cache/cookbooks/aws_security/providers/group.rb:79:in `security_group'
           /tmp/kitchen/cache/cookbooks/aws_security/providers/group.rb:75:in `load_current_resource'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
```

Maybe re-publish to supermarket.chef.io?

**Comment by tas50** [comment]
This was fixed in #36 

A new release needs to get pushed up to the supermarket
